### PR TITLE
fix(notifications): allow inside voice case

### PR DESCRIPTION
**Pull request by emjburns**
Allow notification config in lowercase instead of requiring uppercase.
```json
      "notifications": [
        {
          "type": "slack",
          "address": "#emburns-slack-test",
          "frequency": "verbose"
        }
      ]
```

### CODE REVIEW

**Comment by robfletcher** [comment]
Feels like we could solve this by making enums deserialize in a case-insensitive way rather than having to stick lowercase properties on every enum we use.

**Comment by luispollo** [comment]
@robfletcher I thought about that as well, but wanted to make the parsing backwards-compatible with the upper-case versions, which is achieved with that `@JsonCreator` factory method. I think we could achieve the same thing with a custom (de-)serializer, but it seemed to be more code, not 100% sure.

**Comment by luispollo** [comment]
@emjburns FWIW, if we decide to change approaches, this is the tutorial that was most helpful for me when working on this: https://www.baeldung.com/jackson-serialize-enums

**Comment by emjburns** [comment]
Found a better way!

**Pull request merged**
