### PR TITLE
Java 11 Compatibility

### PR DESCRIPTION
**Pull request by robfletcher**
Fixes a couple of things that didn't work with Java 11, and makes GH Actions use Java 11.

### CODE REVIEW

**Comment by luispollo** [comment]
Neat! Are you intending to actually switch our version in the gradle scripts?

**Comment by gal-yardeni** [comment]
LGTM 👍  Does it mean we'll need to upgrade the java version to have keel running locally?

**Comment by robfletcher** [comment]
> Neat! Are you intending to actually switch our version in the gradle scripts?

The only reference in our Gradle scripts is the `jvmTarget` for Kotlin compilation. I don't believe the base AMI is using Java 11 yet so it makes sense to keep that at 8.

**Comment by robfletcher** [comment]
> LGTM 👍 Does it mean we'll need to upgrade the java version to have keel running locally?

It should be backward compatible.

**Pull request merged**
