### PR TITLE
Turn off Java 8 cross-compilation in CI

### PR DESCRIPTION
**Pull request by robfletcher**

### CODE REVIEW

**Review by plumpy — COMMENTED** [review]
You need to update the mergify config too...

**Comment by robfletcher** [comment]
> You need to update the mergify config too...

D'oh. Thanks. Fixed.

**Review by plumpy — APPROVED** [review]
Hooray!

**Review by luispollo — APPROVED** [review]

**Comment by robfletcher** [comment]
@plumpy if you're happy with this can you merge it? I don't have permission.

**Comment by plumpy** [comment]
Looks like someone set up [branch protection rules](https://docs.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks#enabling-required-status-checks) requiring "build (true)" and "build (false)" to pass before you can merge a PR. I updated the rules to use the "build" status.

**Comment by robfletcher** [comment]
> Looks like someone set up [branch protection rules](https://docs.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks#enabling-required-status-checks) requiring "build (true)" and "build (false)" to pass before you can merge a PR. I updated the rules to use the "build" status.

This PR does that, but because it changed the builds that are happening I then couldn't merge it.

**Pull request merged**
