### PR TITLE
Fixing the environment variable

### PR DESCRIPTION
**Pull request by saimadineni**
This fix will help with resolving the issues related to failures while running keel locally
Issue: https://github.com/spinnaker/keel/issues/1668
A new environment variable called  "${spinnaker.baseUrl} was introduced, which doesn't seem to be necessary. It could have just been gate.baseUrl
 and all the changes related to spinnaker.baseURl? Is this supposed to point to a particular service gate/orca/clouddriver ? With trial and error I was able to figure out that this could possibly be gate. What's the intention behind naming it as spinnaker.baseURL ?
Edit: If it is deck, why can't we just call it the deck url itself instead of calling it the spinnaker baseUrl
Also, I believe there needs to be a section for spinnaker base url in the keel.yml if we need to use spinnkaer base url as the service was failing to run as it couldn't resolve spinnaker base url
spinnaker:
  baseUrl: ${services.deck.baseUrl}
Updated the comment @robfletcher

### CODE REVIEW

**Comment by robfletcher** [comment]
What issues are you seeing?

**Comment by saimadineni** [comment]
Providing more info:
Spinnaker.baseURL environment variable was introduced in this change
https://github.com/spinnaker/keel/blob/master/keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifier.kt#L30

**Comment by emjburns** [comment]
So this variable represents the deck URL (or whatever URL users go to to interact with the UI). We use it for creating contextual links for notifications to help users get directed to the right place. Since it's only used for creating links, we could definitely give it a default garbage value so it doesn't impact local running. Let me put out a pr for that. Thanks for reporting and sorry for the delay in reviewing!

**Comment by emjburns** [comment]
https://github.com/spinnaker/keel/pull/1685

**Pull request closed without merging**
