### PR TITLE
chore(tags): remove entity tagging

### PR DESCRIPTION
**Pull request by emjburns**
Entity tags were a hacky way of showing that a resource was managed. Now that we have a beautiful non-hacky way (https://github.com/spinnaker/deck/pull/7590) we can remove the tagging nonsense!

🗑 Goodbye tags, you do not spark joy 🌈

### CODE REVIEW

**Comment by erikmunson** [comment]
joy

**Comment by asher** [comment]
I think this means we no longer need `MultiRegion.regionalIds` or anything referencing `regionalIds` too, I added that so that entity tags could be scoped to regional ec2 resources maintained via a multi-region spec. They may come in handy later but not sure.

**Comment by robfletcher** [comment]
http://giphygifs.s3.amazonaws.com/media/EReLGTYVBnyXS/giphy.gif

**Comment by emjburns** [comment]
@asher good call! I'll remove that as well.

**Pull request merged**
